// ============================================================================
// VITEST CONFIGURATION FOR COMPACT CONTRACT TESTING
// ============================================================================
//
// This configuration is optimized for testing Compact smart contracts that
// compile to CommonJS JavaScript modules (index.cjs). The key settings are:
//
//   - deps.interopDefault: true — Required for importing CommonJS modules
//     generated by the Compact compiler. Without this, default exports
//     from index.cjs will not resolve correctly.
//
//   - mode: "node" — Ensures Node.js environment for crypto operations
//     used by @midnight-ntwrk/compact-runtime (field arithmetic, hashing).
//
//   - resolve.conditions — Ensures ESM/CJS module resolution works
//     correctly with the mixed module ecosystem of Midnight packages.
//
// Usage:
//   npx vitest run          # Run all tests once
//   npx vitest              # Run in watch mode
//   npx vitest run --reporter=verbose  # Verbose output
//
// ============================================================================

import { defineConfig } from "vitest/config";

export default defineConfig({
  mode: "node",
  test: {
    // interopDefault is CRITICAL for Compact — the compiler generates
    // CommonJS modules (index.cjs) and this setting ensures proper
    // default export handling when importing them in ESM test files.
    deps: { interopDefault: true },

    // Enable global test functions (describe, it, expect) without
    // explicit imports. Reduces boilerplate in test files.
    globals: true,

    // Use Node.js environment for crypto and buffer operations
    // required by the compact-runtime library.
    environment: "node",

    // Standard test file patterns
    include: ["**/*.test.ts"],
    exclude: ["node_modules"],
    root: ".",
  },
  resolve: {
    // Support both TypeScript and JavaScript imports
    extensions: [".ts", ".js"],

    // Module resolution conditions for the Midnight package ecosystem
    conditions: ["import", "node", "default"],
  },
});
